<?php

/**
 * @file
 * Primary module hooks for training_test module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_form_alter().
 */
function training_test_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id === 'node_page_form' || $form_id === 'node_article_form') {
    $form['options']['#open'] = TRUE;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Change title of Promotion Options element in node article form.
 */
function training_test_form_node_article_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['options']['#title'] = "Promotion options for articles";
}
