training_test.hello_world:
  path: '/hello'
  defaults:
    _controller: 'Drupal\training_test\Controller\HelloController::hi'
    _title: 'Training Test Page'
  requirements:
    _permission: 'access content'

training_test.hello_someone:
  path: '/hello/{name}'
  defaults:
    _controller: 'Drupal\training_test\Controller\HelloController::hiSomeone'
    _title_callback: 'Drupal\training_test\Controller\HelloController::title'
  requirements:
    _permission: 'access content'

training_test.hello_someone_node:
  path: '/hello/{name}/{nid}'
  defaults:
    _controller: 'Drupal\training_test\Controller\HelloController::hiSomeoneNode'
    _title: 'Training Test Page Name and Node'
  requirements:
    _permission: 'access content'
